name: test
on: [push]
jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tfausak/hlint-action@v1
  run-test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
      - name: Build
        run: |
          cabal update
          cabal build test-exe
          mkdir ./install
          cabal install --installdir=./install
      - uses: ./hspec-problem-matcher
      - name: Test
        run: ./install/test-exe -f failed-examples
