name: test
on: [push]
jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tfausak/hlint-action@v1
  run-test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
      - name: Build
        run: |
          cabal update
          cabal v2-run test -- --json-failure-report=./hspec-failure-report.json
        continue-on-error: true
      - uses: ./hspec-annotate
        with:
          file: ./hspec-failure-report.json
