name: test
on: [push]
jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.7'
      - uses: rwe/actions-hlint-setup@v1
      - uses: actions/checkout@v2

  build:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: build
        run: |
          cabal update
          cabal v2-build all

  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: lint
        run: hlint --json --no-exit-code ./src ./test > hlint-report.json
      - name: lint-annotate
        uses: ./hlint-annotate/

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: test
        run: ${{ steps.build.outputs.cabal-exe }} v2-run test -- -f github
